### PR TITLE
Add test_000020 - test_000035 (Opus and LPCM focus).

### PR DESCRIPTION
**Pull request by jwcullen**
It is best to wait until #8 is merged as this modifies test_000014.textproto to be consistent with the rest of the Opus tests.

### CODE REVIEW

**Comment by hkchung72** [comment]
test_0000017.iamf is that textproto and decode verication log_output are different.

**Comment by jwcullen** [comment]
So this concern more belongs on issue PR #8. My apologies for the confusiong I may have made the PR's confusing because we were addressing one issue at a time, so they are based on each other.

I'll address the concern with test_000017 here:

This test case was intended to test trimming more than a full frame at the end. So the textproto has a trim value of 200. The Audio Frames in this sample have 64 samples * 2 channels * 16 bits per sample = 256 bytes per `audio_frame`.

The number of samples to trim at end is applied to the last `N` audio frames to trim consecutive audio frames. So for this example with 200 trimmed the last few audio frames has samples trimmed which sum to 200.

Audio Frame 0 has 0 samples to trim at end. (All 64 samples valid)
...
Audio Frame 121 has 8 samples to trim at end. (56 valid samples)
Audio Frame 122 has 64 samples to trim at end. (All samples trimmed)
Audio Frame 123 has 64 samples to trim at end. (All samples trimmed)
Audio Frame 124 has 64 samples to trim at end. (All samples trimmed)

**Comment by kr728-kim** [comment]
Hi, I'm Kyungrae
I joined the test vectors verification tasks.
Nice to meet you :D

In test_000007, we checked that decoder outputs the wrong magic code (ia_code).

**Comment by kr728-kim** [comment]
In test_000008, prototxt's _integrated_loudness_ and _digital_peak_ are different from those in decoder log output.
proto
	integrated_loudness: -13513
        digital_peak: -12879
log
        integrated_loudness: -13733
        digital_peak: -21589

And, we verified that _reinitialize_decoder_ is true from decoder log output.

**Comment by kr728-kim** [comment]
In test_000009, prototxt's _integrated_loudness_ and _digital_peak_ are different from those in decoder log output.
proto
integrated_loudness: -13513
digital_peak: -12879
log
integrated_loudness: -13733
digital_peak: -21589

**Comment by kr728-kim** [comment]
In test_000009, prototxt's _substream_count_ and _coupled_substream_count_ are different from those in decoder log output.
- proto
substream_count: 1
coupled_substream_count: 1
- log
substream_count: 2
coupled_substream_count: 0

**Comment by kr728-kim** [comment]
In test_000011, prototxt's IDs of codec config, audio element, and parameter are different from those in decoder log output.
-proto
codec_config_id: 0
audio_element_id: 0
parameter_id: 0
-log
codec_config_id: 200
audio_element_id: 300
parameter_id: 100

**Comment by kr728-kim** [comment]
In test_000015, prototxt's _integrated_loudness_ and _digital_peak_ are different from those in decoder log output.
- proto
integrated_loudness: -13513
digital_peak: -12879
- log
integrated_loudness: -13733
digital_peak: -21589

**Comment by jwcullen** [comment]
Thank you. Please take note of the `is_valid` field in the textproto. Some tests are invalid bitstreams, so it is good you detected these test cases as invalid:
* test_000007 intentionally has an incorrect magic code which makes it invalid
* test_000008 has reinitialize_decoder set to true which makes it invalid

We have abandoned some previous released test streams when fixing other issues ([634d0e1b](https://github.com/AOMediaCodec/libiamf/pull/9/commits/634d0e1b02bc2cdafdd506c647f407d655ed33ac))
* test_000010
* test_000011

Your concerns about loudness helped us discover an issue in our loudness calculation code for some `is_valid = false` test vectors. 

The textproto did not agree with the .iamf/.mp4 files and in some cases was computed incorrectly in the .iamf/.mp4 files. `is_valid = true` bitstreams were not affected by this bug.
* test_000008 ([01bdf1c8586](https://github.com/AOMediaCodec/libiamf/pull/9/commits/01bdf1c8586c1dadaa8ceb3b7691352e0b6481d0))
* test_000009 (fixed with above)
* test_000015 ([41b7df65](https://github.com/AOMediaCodec/libiamf/pull/10/commits/41b7df655f0b6fc0fdee91017a07ef259681523a))
* And some others
* Since test_000010 and test_000011 have been abandoned they will not be updated and should not be processed anymore.

**Comment by jwcullen** [comment]
Also, please see this chart to understand outstanding PRs. Since we have been fixing and adding features they are dependent on each other. I’m hoping we can get these merged in soon and write issues against outstanding problems because it will be more obvious what is the most recent version.

7 <- 9 (#9 depends on #7 being merged in first)
8 <- 10 <- 11

**Comment by yeroro** [comment]
@hkchung72 @kr728-kim Please note if a test vector is marked as `is_valid: false`, but the decoder did **NOT** reject it, there might be a bug in the decoder. 

Please make sure the decoder correctly rejects invalid test vectors.

**Comment by yeroro** [comment]
In light of people getting confused about files from different PRs and are reviewing out-dated files that are fixed in later PRs, I propose to merge all these early PRs as-is. So everyone can work on the latest revision. 

In the future I will probably also review PRs and merge them soon, and we can deal with bugs and unexpected results through github issues.


> Also, please see this chart to understand outstanding PRs. Since we have been fixing and adding features they are dependent on each other. I’m hoping we can get these merged in soon and write issues against outstanding problems because it will be more obvious what is the most recent version.
> 
> 7 <- 9 (#9 depends on #7 being merged in first) 8 <- 10 <- 11

**Review by yeroro — APPROVED** [review]

**Comment by jwcullen** [comment]
The scope of this PR was intended to introduce test_000020 -> test_000035. I addressed all comments on this PR, but they were all related to test vectors introduced or modified most recently in other PRs.

I think we should merge this in with the understanding #13 is still open. If there are more issues they can be written in the issues section.

Please note #10 should be merged in before this PR.

**Comment by kr728-kim** [comment]
@jwcullen @yeroro We already know there are some `is_valid: false` test vectors. I informed you of the invalid test cases of test_000007 and test_000008 in that we detected your intention.

From now on, I will report the test vector validation results in the issues section.

**Pull request merged**
