### PR TITLE
Fix #77: Update IAMF files with `iacb` atom and new semantics.

### LINKED ISSUE #77: MP4 files need to be updated according to PR #794 and #795

### PR DESCRIPTION
**Pull request by jwcullen**
- Also, re-encode Opus files with `opus_encode_float`.
  - Drop `test_000013`.

### CODE REVIEW

**Comment by sunghee-hwang** [comment]
> * Also, re-encode Opus files with `opus_encode_float`.
> * Drop `test_000013`.

Regarding re-encode Opus files, is there any special reason to change bitstreams? 
If not, how about just keeping the original bitstreams?
If you feel still need to check it, how about creating a new test case for it?

**Comment by jwcullen** [comment]
We switched the implementation of the Opus portion of the encoder, but you are right that it is better to minimize changes here.

I can regenerate them based on the old implementation tomorrow. This should keep the standalone bitstream the same.

This shouldn't affect the LPCM, FLAC, and AAC ones in this PR which can be used for initial validation.

**Comment by jwcullen** [comment]
After further investigation this PR also captures other bug-fixes in the encoder which led to bugs in the bitstream (see #82 for more details).

Choose one of this PR or #82 and then close the other without merging it in.

**Comment by sunghee-hwang** [comment]
This PR is closed as PR #82 is chosen to be merged.

**Pull request closed without merging**
