### PR TITLE
Update test vectors to address issue #6

### PR DESCRIPTION
**Pull request by jwcullen**
This should resolve the issues brought up in issue #6 .

### CODE REVIEW

**Comment by jwcullen** [comment]
I just force pushed to change the commit message to refer to the correct issue #6. Everything else is the same.

**Comment by yilun-zhangs** [comment]
Hello,

To TC 12,
I checked the samples of last frame in test_000012_s.mp4 and test_000012_f.mp4, still is 62, 
so, after decoding, the total samples will be 124*64 + 62 = 7998, which is not match with the samples of original file (sawtooth_100_stereo.wav).

audio_frame_metadata {
  wav_filename: "sawtooth_100_stereo.wav"
  substream_metadata {
    key: 0
    value {
      channel_ids: [0, 1]
    }
  }
  substream_id_ordering: [0]
  samples_to_trim_at_end: 2
  samples_to_trim_at_start: 0
}

Thanks.

**Comment by yeroro** [comment]
Yeah we will provide the decoded WAV file for this.

**Comment by yeroro** [comment]
> Yeah we will provide the decoded WAV file for this.

What I meant is we will provide decoded WAV files in a different PR, and I would like this to be merged as is.

**Comment by jwcullen** [comment]
The scope of this PR was intended to resolve everything mentioned in #6. So if this PR resolves #6 it should be merged in. The wav for 000012 is in PR#9.

**Review by yeroro — APPROVED** [review]

**Pull request merged**
