### PR TITLE
V1.1 test vectors

### PR DESCRIPTION
**Pull request by jwcullen**
Add "Test Set 6": test_000600 - test_000633 in 0471b3b.

Based on "Set0-Expanded_ "Immersive_Audio_Container/[240729]IAMF_Ref_SW_V1.1_additional_TCs.xlsx"
 in this [post](https://groups.aomedia.org/g/WG-Storage-and-Transport/message/884). Except the tests are indexed so the first one is 600 instead of 601.

A case using 4OA + Top-4Ch was changed to 3OA + Top-4Ch to fit within the 28 channel limit. Similar for another case with 4OA + Top-6Ch. 

Another "Test Set 7" is ~~planned and will be added as commits on this PR~~ test_000700 - test_000711 in f6c1a1a.

This PR is a superset of #116 and should merged after it.

### CODE REVIEW

**Comment by sunghee-hwang** [comment]
@felicialim @jwcullen can you resolve the conflict?

**Comment by yongmin-kwon** [comment]
We have tested the added layouts and maximum number of channels, elements, etc., using the provided bitstreams. 
As a result, it showed a PSNR value of over 99 dB with reference. Thank you.

**Review by yongmin-kwon — COMMENTED** [review]
We have tested the added layouts and maximum number of channels, elements, etc., using the provided bitstreams.
As a result, it showed a PSNR value of over 99 dB with reference. Thank you.

**Review by yongmin-kwon — APPROVED** [review]

**Comment by jwcullen** [comment]
Re-synced with main and ready to merge in.

**Pull request merged**
