### PR TITLE
Specify which parts of the software is informative

### PR DESCRIPTION
**Pull request by Frank-Ba**

### CODE REVIEW

**Comment by hkchung72** [comment]
Why does not the m2m_rdr.c include this text?

/*
AOM-IAMF Standard Deliverable Status:
This software module is out of scope and not part of the IAMF Final Deliverable.
*/

**Comment by yilun-zhangs** [comment]
The functions in downmix_render.c are also used to do audio rendering(multichannel to multichannel with demix information).
So I think this file also need to include this text.

/*
AOM-IAMF Standard Deliverable Status:
This software module is out of scope and not part of the IAMF Final Deliverable.
*/

@hkchung72 
How  do you think about this?

**Comment by Frank-Ba** [comment]
> The functions in downmix_render.c are also used to do audio rendering(multichannel to multichannel with demix information).
> So I think this file also need to include this text.

> /*
> AOM-IAMF Standard Deliverable Status:
> This software module is out of scope and not part of the IAMF Final Deliverable.
> */
@yilun-zhangs please refer to the PR https://github.com/AOMediaCodec/iamf/pull/726. Any mixing operations such as this downmix implementation is part of the mixer in Figure 2.

**Comment by Frank-Ba** [comment]
> There would be two kinds of downmixings in the IAMF spec. One is to use downmix matrixes (informative) and the other is to use demixing info which is delivered in bitstream (normative).

@sunghee-hwang does your comment mean that we should change something in this PR?

**Comment by sunghee-hwang** [comment]
> > There would be two kinds of downmixings in the IAMF spec. One is to use downmix matrixes (informative) and the other is to use demixing info which is delivered in bitstream (normative).
> 
> @sunghee-hwang does your comment mean that we should change something in this PR?

I just tried to convey the fact. If you ask my suggestion, then I would suggest the following:
- m2m_rdr.c needs to add the informative text
- downmix_render.c needs no change.

**Comment by Frank-Ba** [comment]
> m2m_rdr.c needs to add the informative text

Okay, I saw that change in the PR.

**Review by hkchung72 — APPROVED** [review]
it looks good, thanks.

**Pull request merged**
