### PR TITLE
Fix #78,#79: Update mp4 demux with `iacb` box, update descriptors parsi…

### LINKED ISSUE #78: MP4 demux needs to be updated according to PR #794

### PR DESCRIPTION
**Pull request by yilun-zhangs**
…ng logic

### CODE REVIEW

**Comment by yilun-zhangs** [comment]
fix #78 , #79

**Review by kr728-kim — APPROVED** [review]

**Comment by yilun-zhangs** [comment]
fix #85

**Comment by yilun-zhangs** [comment]
fix #89

**Comment by yilun-zhangs** [comment]
fix #87

**Comment by jwcullen** [comment]
Since this PR brings in `.clang-format` file, I updated the README to refer to it. Previously it referred to another repository.

**Pull request merged**
