### PR TITLE
Add initial IAMF decoder version(Specification frozen, 2023-07-18)

### PR DESCRIPTION
**Pull request by yilun-zhangs**
It is based on the spec which is updated to https://github.com/AOMediaCodec/iamf/pull/428

### CODE REVIEW

**Comment by yilun-zhangs** [comment]
Need further opensource reviewing, close firstly.

**Review by hkchung72 — APPROVED** [review]
Thanks, LGTM

**Comment by yilun-zhangs** [comment]
> 

As I have checked the code in libiamf, I find code/LICENSE file and the license in the README have been modified same by 3ffd9f2dc8ee42bf722bc8d07e5e43aaa5adc9a2

The code in Samsung/iac dose not update for long time, so license is not match, I will update it as well.

Thanks.

**Comment by felicialim** [comment]
> (also, it might be good to report in the README that the bundled codecs in dep_codecs/ are under their own license, and include a copy of those. It may be better to not include the binaries at all, if possible)

If they are included, it would be good to have them a third_party/ directory along with their LICENSE files (e.g., [1]).

[1] https://aomedia.googlesource.com/aom/+/refs/heads/main/third_party/

**Pull request merged**
