### PR TITLE
Delete tests/test_000000.py

### PR DESCRIPTION
**Pull request by kr728-kim**
Delete tests/test_000000.py used only at the beginning of the conformance test for IAMF v1.0.

### CODE REVIEW

**Comment by jwcullen** [comment]
LGTM, should [README_Primitive_Test.md](https://github.com/AOMediaCodec/libiamf/blob/main/tests/README_Primitive_Test.md) also be deleted (here or in another PR is fine)?

**Comment by felicialim** [comment]
lgtm, how about test_000000_3.log and ss0*.wav, are they still relevant?

**Comment by kr728-kim** [comment]
> LGTM, should [README_Primitive_Test.md](https://github.com/AOMediaCodec/libiamf/blob/main/tests/README_Primitive_Test.md) also be deleted (here or in another PR is fine)?

Yes, I think so. I will delete it here.

**Comment by kr728-kim** [comment]
> lgtm, how about test_000000_3.log and ss0*.wav, are they still relevant?

They are not relevant now. I will delete them here.

**Review by felicialim — APPROVED** [review]

**Review by yilun-zhangs — APPROVED** [review]
LGTM

**Pull request merged**
